const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const progress=q('.progress'),nav=q('.nav'); addEventListener('scroll',()=>{let h=document.documentElement;progress.style.width=(h.scrollTop/(h.scrollHeight-h.clientHeight)*100)+'%';nav.classList.toggle('scrolled',scrollY>30)});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});qa('[data-reveal]').forEach(e=>io.observe(e));
if(matchMedia('(pointer:fine)').matches){const dot=q('.cursor-dot'),ring=q('.cursor-ring');addEventListener('mousemove',e=>{dot.style.left=ring.style.left=e.clientX+'px';dot.style.top=ring.style.top=e.clientY+'px'});qa('a,button,.tilt').forEach(e=>{e.addEventListener('mouseenter',()=>ring.classList.add('hover'));e.addEventListener('mouseleave',()=>ring.classList.remove('hover'))});qa('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{let r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform=`translate(${x*.13}px,${y*.13}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});qa('.tilt').forEach(el=>{el.addEventListener('mousemove',e=>{let r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.setProperty('--mx',((x+.5)*100)+'%');el.style.setProperty('--my',((y+.5)*100)+'%');el.style.transform=`perspective(900px) rotateX(${-y*5}deg) rotateY(${x*6}deg) translateY(-2px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}
const tl=q('.timeline'),detail=q('.timeline-detail');qa('.milestone').forEach(m=>m.onclick=()=>{qa('.milestone').forEach(x=>x.classList.remove('active'));m.classList.add('active');detail.innerHTML=`<span>${m.dataset.year}</span><h3>${m.dataset.title}</h3><p>${m.dataset.detail}</p>`;tl.classList.add('expanded')});q('.timeline-toggle').onclick=()=>tl.classList.toggle('expanded');
q('.copy').onclick=async e=>{try{await navigator.clipboard.writeText(e.currentTarget.dataset.copy);q('.copy-status').textContent=document.documentElement.lang.startsWith('zh')?'已复制电话号码':'Phone number copied';setTimeout(()=>q('.copy-status').textContent='',1800)}catch{}};
// ambient starfield
const c=q('#stars'),ctx=c.getContext('2d');let pts=[];function resize(){let d=devicePixelRatio||1;c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);pts=Array.from({length:Math.min(150,Math.floor(innerWidth/8))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.3+.2,a:Math.random()*.7+.15,v:Math.random()*.08+.02}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of pts){p.y-=p.v;if(p.y<0)p.y=innerHeight;ctx.beginPath();ctx.fillStyle=`rgba(150,205,255,${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}resize();addEventListener('resize',resize);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)draw();

// Signature V2 pointer-reactive lighting and hero depth
const root=document.documentElement;
addEventListener('pointermove',e=>{root.style.setProperty('--px',e.clientX+'px');root.style.setProperty('--py',e.clientY+'px');});
const stage=q('.portrait-stage'),portrait=q('.portrait-wrap');
if(stage&&portrait&&matchMedia('(pointer:fine)').matches){stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;portrait.style.rotate=`${-y*3}deg ${x*5}deg`;});stage.addEventListener('pointerleave',()=>portrait.style.rotate='');}
// animate numbers/years into view without changing factual values
qa('.degree>b,.milestone>span').forEach((el,i)=>{el.animate([{opacity:.35,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:900,delay:200+i*110,fill:'both',easing:'cubic-bezier(.2,.7,.2,1)'});});
